### ISSUE TITLE
synch with ecmwf upstream

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/fckit#21]
merge upstream changes into our forks and issue upstream pull requests for remaining differences

- [x] fckit
- [ ] ecbuild
- [x] eckit
- [x] atlas
- [x] odc
- [x] pyodc

This may be a fairly significant undertaking.  A quick look at fckit reveals a dozen conflicts

**Comment by aerorahul** [comment]
I can take care of atlas, I think.  I have been using the ecmwf repo for most of the work anyway.
I can take a look at ecbuild, but those should be minor.

**Comment by benjaminmenetrier** [comment]
I have looked at the differences between the `develop` branches of ECMWF and JCSDA, and it looks like they have pushed a lot more commits than us (95/13). Moreover, most of our commits since the last sync on Dec 6, 2018 are very minor (often less than 3 files impacted). So it seems reasonable to start from their branch and to add our modifications in it.

In the branch `feature/towards_sync_with_ecmwf`, you will find 3 commits:
1) The first commit is just a sync with ECMWF `develop` branch.
2) The second commit adds our own modifications. I think that all these changes should be acceptable by ECMWF, so we can issue a pull-request with all of them. I have followed the successive commits in our repo:
   - More ECKIT interfaces (spherical geometry and kdtree)
   - New configuration functions (`get_size`, `get_array_logical` and `get_array_string`)
   - Minor change required to remove `config_mod` from OOPS
   - Add directory label for CDash
   - Add a constructor for `fckit_mpi_comm`
   - Remove developer-only warnings from release builds
   - Public access to pointer required for IODA (I have uncommented the line giving a public access to the C pointer of fckit shared objects, required in IODA).
3) The third commit includes our deprecated interfaces for the `get_array_string` function, for backward compatibility. This one will not be sent to ECMWF.

I have omitted the commit "Update to upstream ecmwf/fckit-0.6.3 with support for eckit-1.1.0" on Jul 25, 2019, because I don't know what is coming from ECMWF and what is new in it. @markjolah and @mmiesch could you tell me if they are some features of this commit that you would like to merge in ECMWF repo?

The next steps for a smooth transition should be:
1) Test the branch `feature/towards_sync_with_ecmwf` with all repos. I have passed all the tests on my workstation with GNU 8.4.0 for SABER, OOPS, FV3-JEDI, SOCA and MPAS. Please test on your machines.
2) Add a few tests for the new functionalities we have added.
3) Send a PR to ECMWF, go through the review process and get things merged. The branch is ready but I don't have the push permission (I just requested it).
4) Sync our `develop` with their `develop` and add the deprecated interfaces for `get_array_string`.
5) Remove the calls to deprecated interfaces from SABER, OOPS, and all models.
6) Remove the deprecated interfaces in FCKIT, and we'll be perfectly in sync with ECMWF!

Please let me know what you think about this procedure and about the code.

**Comment by mmiesch** [comment]
Thanks @benjaminmenetrier for your work on this.  This plan sounds great.  I think most of that Jul 25 PR was just merging in changes from ecmwf so I don't have anything else from that PR that needs to be added.  I tested this branch with fv3-bundle on my Mac (gnu/openmpi) and on AWS (intel19) and everything looks good.

**Comment by benjaminmenetrier** [comment]
Hello, I have just sent two PRs on ECMWF repos for `eckit` and `fckit`:
 - https://github.com/ecmwf/eckit/pull/26 
 - https://github.com/ecmwf/fckit/pull/11

Could you please sign the licence agreements (required to start the review!):
 - for eckit: @markjolah and @rhoneyager 
 - for fckit: @markjolah, @rhoneyager and @cmgas.

The branches are called `develop-jcsda`. For fckit, the branch `feature/towards_sync_with_ecmwf`, which is based on `develop-jcsda` but includes deprecated interfaces, should be used to test things in our systems.

I noticed that a few code modifications are required in OOPS and UFO:
 - https://github.com/JCSDA/oops/pull/618
 - https://github.com/JCSDA/ufo/pull/891

They are compatible with the current versions of `eckit` and `fckit`, so they could be merged anytime.

**Comment by mmiesch** [comment]
If we're happy with [this plan](https://github.com/JCSDA/fckit/issues/22) to synch our develop and master branches nightly with ecmwf I think we should start implementing it.

odc and pyodc are already ready.

atlas is already ready as well in the sense that our develop branch is already in synch.  There is a develop-jcsda branch that still exists and is not in synch.  Is anyone using that?  Can we delete it?

fckit isn't quite ready but @benjaminmenetrier has a plan - see above. I think we should tag his feature/towards_sync_with_ecmwf branch and use that tag now in our bundles.  We won't be able to use ecmwf tags/releases until our pr is merged and we remove the deprecated interfaces in all of our repos.  But, if we use the tag in our bundles, then we could in principle start synching our develop right away.  Is there anything in develop that is *not* in either develop-jcsda or feature/towards_synch_with_ecmwf?  However, we would need to update all the bundle repos first and warn everybody that we're doing this.

It should be easier for eckit - there we are already using  tagged version in the containers & modules and I think most of the bundles.  BM has isolated our changes, put them in the develop-jcsda branch, and issued an upstream PR.  So, I think there we could start synching develop pretty much immediately, after posting a warning on the GitHub team page to use the latest jcsda tag.

ecbuild - After the recent merge, we're almost up to date with ecmwf develop, apart from a few commits in the last few weeks.  I tagged this as 3.3.0.jcsda1 and we can use this in our bundle, modules, and containers.

There are a few changes in our develop that are not in ecmwf.  I have divided these into three new branches so we can stage them for upstream PRs - if we keep them focused they'll be more likely to review them in a timely manner:
- feature/FindNetCDF
- feature/get_test_data
- bugfix/intel_shlib_undefined

I can do the upstream PRs for these if you wish or the authors can do them (@markjolah, @mer-a-o) - either way.  

Now that we have the tag and these branches staged for the PRs, develop is no longer needed.  So, I believe ecbuild is also ready for nightly synching with ecmwf.

If everyone is ok with this, I can work with @rickgrubin to start implementing this for the repos that are ready, using @aerorahul's git synch script.

**Comment by ytremolet** [comment]
Please don't delete develop-jcsda in atlas, we still need it. But it's not working so don't try to merge it. Once develop is up to date I'll move what's needed in a feature branch.

**Comment by benjaminmenetrier** [comment]
Hello. I was waiting for an answer of Tiago Quintino for the ECKIT PR at ECMWF : https://github.com/ecmwf/eckit/pull/26, but it never came and I forgot... sorry. It looks like we can remove our contributions about KDNode and the Intel bugfix. 

However, I would like to know what you think about Willem's comments on the `Test.h` contribution (@wsmigaj) and on the `EXPECT_EQUAL` question (@wsmigaj and @mmiesch). I mention @markjolah and @rhoneyager since they were also contributors.

Once I have your opinions, I'll update the branch accordingly and ask Willem for review and merge.

**Comment by mmiesch** [comment]
Thanks @benjaminmenetrier - I agree to remove our contributions on the KDNode and intel bugfix.

I do not have any strong feelings about the other two.  I'm ok with the solutions they propose upstream as long as @wsmigaj is happy.

**Comment by wsmigaj** [comment]
@benjaminmenetrier The ``KDNode`` and ``Test.h`` contributions have already been merged into ECMWF's ``eckit`` (https://github.com/ecmwf/eckit/pull/18 and https://github.com/ecmwf/eckit/pull/19). Tiago has said he is working on something similar to ``EXPECT_EQUAL`` (https://github.com/ecmwf/eckit/issues/20).

So the ``KDNode``, ``Test.h`` and ``EXPECT_EQUAL`` contributions can be removed from https://github.com/ecmwf/eckit/pull/26. However, if we want to start using ECMWF's version of ``eckit`` after that PR is merged, we'll need to put a definition of ``EXPECT_EQUAL`` in ``oops``, unless by that time Tiago adds a similar feature to ``eckit``.

**Comment by benjaminmenetrier** [comment]
Thanks @wsmigaj. So it looks like all JCSDA's contributions except the `EXPECT_EQUAL` function are already merged into ECMWF's `eckit`. Two options here: should we wait for a merge of https://github.com/ecmwf/eckit/issues/20, or should we add a definition in `oops` as @wsmigaj suggests? What are the time constraints?

**Comment by wdeconinck** [comment]
ECMWF's eckit develop branch now has `EXPECT_EQUAL` [https://github.com/ecmwf/eckit/issues/20#issuecomment-626688796]

**Comment by benjaminmenetrier** [comment]
With the latest commit from @wdeconinck, the ECKIT `develop` at ECMWF can be used with all the `feature/pointlonlat_fortran_interface` branches of JCSDA's repos.

**Comment by benjaminmenetrier** [comment]
ATLAS is ready: the `ecmwf/develop` branch can be used with our `feature/pointlonlat_fortran_interface` branches. The `feature/pointlonlat_fortran_interface` of ATLAS includes additional interfaces with the `Point` class that are not merged yet, but they are not used anywhere in our codes.

**Comment by mmiesch** [comment]
I think we can triumphantly close this issue - finally!  Thanks all for your help.
