### ISSUE TITLE
Management of ECMWF forks

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/fckit#22]
I thought this should be a separate issue from #21 so it doesn't get lost in the details of our other updates.

We should come up with a way to manage our ecmwf forks: eckit, fckit, ecbuild, atlas, odc, pyodc.    Here is what I suggest for each of these repos, based on discussions with several others.

* We keep our develop branch in sync with ecmwf develop.  We should pull upstream on a daily or weekly basis.

* We can create our branches (feature, bugfix, etc) from our own develop branch.  Then we should do a pull request upstream.  No PRs to our develop - the only way our develop changes is by synching with upstream.

* We use tagged versions of each repo in our bundles, containers, and environment modules.  Since our develop is synchronized with upstream, the tags would be as well.

* if we need a particular feature to make our bundles work, then we can use that feature branch in our bundles until it is available upstream.

The disadvantage of this approach is that if there is some feature that we need that they do not accept upstream in a timely manner, then we would need to use feature branches in our bundles indefinitely.  For this reason, it might be advisable to maintain a jcsda-develop branch.  But, if we permit the existence of a jcsda-develop branch, then I think it is bound to diverge.  We have already seen that happen.  So, I think we should stick with a single develop branch and be patient with upstream to get our changes in.

Any thoughts?

**Comment by ytremolet** [comment]
I agree with the approach. I would just add, make sure our develop is in sync before issuing a PR upstream and the feature branch on top of the latest develop (as it should always be).

If there are issues with upstream merges we'll discuss that, for now let's assume in most cases there won't be.

**Comment by benjaminmenetrier** [comment]
Thank you @mmiesch for this simple and clean plan, I agree with it totally. I don't worry for the PRs upstream with `atlas` and `fckit` since Willem is always answering quickly. `eckit` will not not be modified very often, so it should not be an issue. I don't know about other repos.

**Comment by srherbener** [comment]
@mmiesch, I think this will work fine.

I've already created develop-jcsda branches in our forks of odc an pyodc since I wanted to be able to put tags on this branch. However, tags really go on commits don't they? If that is true then I should be able to stop using develop-jcsda branches, and I agree that it's cleaner without the develop-jcsda branches.

Should I just rename the develop-jcsda branches to feature/xxx in our forks? I've already submitted PRs to  ECMWF from the develop-jcsda branches so would github keep track of that if I rename the branches in our fork?

Thanks!

**Comment by wdeconinck** [comment]
You should never make PRs from a "develop-jcsda" or any "develop" branch, as these are moving branches (because you yourself may combine different features) that keep being appended in the PR muddling up the PR, if the PR is not immediately merged.
PRs should ideally be feature branches rebased on the most recent upstream develop, so as to make the process as easy and clean as possible.

**Comment by srherbener** [comment]
@wdeconinck, thanks for the feedback! I understand the issue you have mentioned. I'll go clean up the mess I created with the odc and pyodc forks.

**Comment by aerorahul** [comment]
Isn't jcsda/develop-jcsda treated as any other "feature" branch in this case, when a PR is issued to upstream/develop? The jcsda/develop then is just a synchronized version of the upstream/develop.

The upside to this is upstream/develop won't get bombarded with every single JCSDA development PR (this can be good and bad).  Sometimes you want bugfixes reported upstream faster, and that still can be done. 

Just my thoughts. What am I missing?

**Comment by wdeconinck** [comment]
What I mean is that certain parts of the develop-jcsda may be perfectly agreeable to be merged upstream, and if they were in a separate PR that would be done quickly. If it isn't agreeable, then the PR may not be merged in, but also don't get possibility to be reworked as other merges have happened into the develop-jcsda branch in the mean time (e.g. other features).
Or vice versa, a at first sight agreeable PR has become unagreeable because of further merges in the develop-jcsda branch that get appended to the PR and the PR even may lose its original intention.

**Comment by ytremolet** [comment]
I agree that there should be one PR per feature. That's what we are trying to do for all our work, not just when working with a fork. I don't think there should be any difference.
